#+title: text

* ch 2: Matter

** The Nature of Matter

Key Terms
• Matter
• Atoms
• Compounds
• Molecule
• Elements
• Solid
• Liquid
• Gas

Objectives
• To learn about the composition of matter
• To learn the difference between elements and compounds
• To define the three states of matter

A. The Particulate Nature of Matter

Matter, the “stuff” of which the universe is composed, has two characteristics: it has mass and it occupies space. Matter comes in a great variety of forms: the stars, the air that you are breathing, the gasoline that you put in your car, the chair on which you are sitting, the turkey in the sandwich you may have eaten for lunch, the tissues in your brain that allow you to read and understand this sentence, and so on.

As we look around our world, we are impressed by the great diversity of matter. Given the many forms and types of matter, it seems difficult to believe that all matter is composed of a small number of fundamental particles. It is surprising that the fundamental building blocks in chocolate cake are very similar to the components of air.

The Atomic Nature of Matter

How do we know that matter is composed of the tiny particles we call atoms? After all, they are far too small to be seen with the naked eye. It turns out that after literally thousands of years of speculation, we can finally “see” the atoms that are present in matter. In recent years scientists have developed a device called a scanning tunneling microscope (STM) that, although it works quite differently from an optical microscope, can produce images of atoms. For example, look at the penny shown in Figure 2.1. The small objects represent tiny copper atoms. When chemists look at other metals with powerful microscopes, they see atoms in these substances as well. With ultra-high magnification, objects appear more similar. All objects are made up of small particles called atoms.

All matter consists of tiny particles called atoms. But when you look at objects such as nails or pennies, you don’t see these particles. Why not? The atoms are very tiny and can be seen only with a powerful magnifying instrument. You may have encountered the same concept in your life when you looked at a beach from a distance. The sand looks uniform—you can’t see the separate particles. As you get close, however, the individual grains of sand become apparent. Observe the Impressionist painting by Seurat shown in the photo on the following page. From a distance the scene looks normal. Only when you stand very close to the painting do you see that it is composed of tiny dots of paint.

So, the conclusion is that although objects in the macroscopic world typically look quite continuous and uniform, they are really particulate in nature—they are made of atoms. We can “see” them with powerful electronic microscopes.

B. Elements and Compounds

We have just considered the most important idea in chemistry: matter
is composed of tiny particles we call atoms. If all matter is made up of
tiny particles called atoms, are all atoms alike? That is, is copper metal
made of the same kind of atoms as gold? The answer is no. Copper atoms
and gold atoms are different. Scientists have learned that all matter is com-
posed from about 100 different types of atoms. For example, air is mostly
gaseous oxygen and nitrogen. The nitrogen atoms are different from the
oxygen atoms, which in turn are different from copper atoms, which differ
from gold atoms.

You can think of the matter in the universe like the words in a book. If you
break all the words in this book apart into their component letters, you will
end up with “large piles” of only 26 letters. The English alphabet allows you
to construct thousands of words from just 26 letters. Similarly, all the matter
in the universe is constructed by putting approximately 100 types of atoms
together in various ways. The different types of matter are like the different
words in a book. When we separate all of the universe into its atoms, we find
approximately 100 different atoms. We call these 100 types of atoms the
elements of the universe.

To illustrate this idea, consider the letters A, D, and M. Using these letters
you can make many words, such as MAD, DAM, DAD, and MADAM (can you
think of others?). Each word represents something very different. Thus, with
only three letters, you can represent several unique things or ideas.

Compounds

In much the same way that we can use a few letters to make thousands
of words, we can use a few types of atoms to construct all matter. For
example, consider the atoms hydrogen, oxygen, and carbon:
Hydrogen
Oxygen
Carbon
Notice that we represent atoms by using spheres. We get this idea from
the highly magnified pictures of metals that show the atoms. Notice in
Figure 2.1 that atoms look like spheres.
We can combine the hydrogen, oxygen, and carbon atoms in a variety
of ways. Just as letters combine to form different words, atoms combine to
form different compounds. Compounds are substances made by bonding
atoms together in specific ways. These substances contain two or more
different types of atoms bound together in a particular way. A specific
compound consists of the same particles throughout. Table 2.1 shows
some examples of atoms combined into compounds.

Consider a glass of water. If you could magically travel inside the water
and examine its individual parts, you would see particles consisting of two
hydrogen atoms bonded to an oxygen atom:

Molecule
A collection of atoms
bonded together that
behave as a unit


We call this particle a molecule. A molecule is made up of atoms that
are “stuck” together. A glass of water, for example, contains a huge number
of molecules packed closely together (see Figure 2.3).
Carbon dioxide is another example of a compound. For example, “dry
ice”—solid carbon dioxide—contains molecules of the type
packed together as shown in Figure 2.4.

C. The States of Matter

Water is one of the most familiar substances in our world. We recognize
water in three different states: solid, liquid, and gas. If we lower the temperature
of liquid water, it freezes—that is, it changes to ice (solid water). On the other
hand, if we heat water to its boiling point, it “disappears” into the air as a gas.
The three states of water have distinctly different properties. If a pond
freezes in the winter, you can walk across it. Solid water can support your
weight. Conversely, you would never try to walk across the same pond in
the summertime!
We can also highlight the differing properties of liquid and solid water
with food coloring. A drop of food coloring placed on an ice cube just sits
there on top of the ice. In contrast, a drop of food coloring placed in liquid
water spreads throughout the liquid. The fact that the food coloring spreads
in all directions in the liquid water indicates that the water molecules must
be moving, bouncing the “food coloring molecules” around and keeping
them suspended. This property is very different from that of ice, where the
food coloring does not penetrate the surface. Also, we know that gaseous
water is quite different from solid and liquid water because it is invisible
to the naked eye, unlike the other states of water.
Like water, all substances exist in the three states of matter: solid, liquid,
and gas. A solid is rigid. It has a fixed shape and volume. A liquid has
a definite volume but takes the shape of its container (see Figure 2.7).
A gas has no fixed volume or shape. It uniformly fills any container.

** properties of matter

Objectives

• To learn to distinguish between physical and chemical properties
• To learn to distinguish between physical and chemical changes
Key Terms

• Physical properties
• Chemical properties
• Physical changes
• Chemical change

A. Physical and Chemical Properties and Changes

When you see a friend, you immediately respond and call him or her by
name. We can recognize a friend because each person has unique characteris-
tics or properties. The person may be thin and tall, may have brown hair and
blue eyes, and so on. These characteristics are examples of physical proper-
ties. Substances also have physical properties. The typical physical properties
of a substance include odor, color, volume, state (gas, liquid, or solid), density,
melting point, and boiling point.

We can also describe a pure substance in terms of its chemical properties,
which refer to its ability to form new substances. An example of a chemical
change is wood burning in a fireplace, giving off heat and gases and leaving
a residue of ashes. In this process, the wood is changed to several new sub-
stances. Other examples of chemical changes include the rusting of steel, the
digestion of food, and the growth of plants. In a chemical change a given
substance changes to a fundamentally different substance or substances.

Physical property
Characteristic of a
substance that can change
without the substance's
becoming a different
substance

Chemical property
Active Reading Question
Characteristic that
describes the ability of
a substance to change
to a different substance

Matter can undergo changes in both its physical and its chemical
properties. To illustrate the fundamental differences between physical and
chemical changes, we will consider water. As we have seen, a sample of
water contains a very large number of individual units (called molecules),
each made up of two atoms of hydrogen and one atom of oxygen—the
familiar H2O, which can be represented as:

Here the letters stand for atoms and the lines show attachments, called
bonds, between atoms. The molecular model on the right represents water
in a more three-dimensional fashion.
What is really occurring when water undergoes the following changes?
Solid
(ice)
Liquid
(water)
Melting
Gas
(steam)
Boiling
When ice melts, the rigid solid becomes a mobile liquid that takes the
shape of its container. Continued heating brings the liquid to a boil, and
the water becomes a gas or vapor that seems to disappear into the air. The
changes that occur as the substance goes from solid to liquid to gas are
represented in Figure 2.8. In ice the water molecules are locked into fixed
positions. In the liquid the molecules are still very close together, but some
motion is occurring; the positions of the molecules are no longer fixed as
they are in ice. In the gaseous state the molecules are much farther apart
and move randomly, hitting each other and the walls of the container.

The most important thing about all these changes is
that the water molecules are still intact. The motions of
individual molecules and the distances between them
change, but H2O molecules are still present. These changes of
state are physical changes because they do not affect the
composition of the substance. In each state we still have
water (H2O), not some other substance.
Now suppose that we run an electric current through
water as illustrated in Figure 2.9. Something very dif-
ferent happens. The water disappears and is replaced by
two new gaseous substances, hydrogen and oxygen. An
electric current actually causes the water molecules to
come apart—the water decomposes to hydrogen and
oxygen. We can represent this process as follows:
Water
Oxygen
gas forms
Hydrogen
gas forms
Electrode
Source of
direct current
Electric
current
This is a chemical change because water (consisting of
H2O molecules) has changed into different substances:
hydrogen (containing H2 molecules) and oxygen
(containing O2 molecules). In this process, the H2O
molecules have been replaced by O2 and H2 molecules.
Let us summarize as follows.

* ch 3: Chemical Foundations: Elements, Atoms, and Ions

** The Elements

Key Term
• Element symbols

Objectives
• To learn about the relative abundances of the elements
• To learn the names of some elements
• To learn the symbols of some elements

The Greeks were the first to try to explain why chemical changes occur.
By about 400 B.C. they had proposed that all matter was composed of four
fundamental substances: fire, earth, water, and air.
The next 2000 years of chemical history were dominated by alchemy.
Some alchemists were mystics and fakes who were obsessed with the idea of
turning cheap metals into gold. However, many alchemists were sincere sci-
entists and this period saw important events: the elements mercury, sulfur,
and antimony were discovered, and alchemists learned how to prepare acids.
As we saw in Chapter 2, all of earth’s materials (and those of other parts
of the universe) can be broken down chemically into about 100 different
elements. At first it might seem amazing that the millions of known substances
are composed of so few fundamental elements. Fortunately for those trying to
understand and systematize it, nature often uses a relatively small number of
fundamental units to assemble even extremely complex materials. For example,
proteins, a group of substances that serve the human body in almost uncount-
able ways, are all made by linking together a few fundamental units to form
huge molecules. A nonchemical example is the English language, in which
hundreds of thousands of words are constructed from only 26 letters.
Compounds are made by combining atoms of the various elements, just
as words are constructed from the 26 letters of the alphabet.

Just as you had to learn the letters of the alphabet before you could learn to
read and write, you need to learn the names and symbols of the chemical
elements before you can read and write chemistry.

A. Abundances of Elements

At present, about 115 different elements are known, 88 of which occur
naturally. (The rest have been made in laboratories.) The elements vary
greatly in abundance. In fact, only nine elements account for most of
the compounds found in earth’s crust. In Table 3.1, the elements are listed
in order of abundance (mass percent) in earth’s crust, oceans,
and atmosphere.

Oxygen, in addition to accounting for about 20 percent of earth’s atmo-
sphere (where it occurs as O_2 molecules), is also found in virtually all rocks,
sand, and soil on earth’s crust. In these materials, oxygen is not present as
O2 molecules but exists in compounds that usually contain silicon and
aluminum atoms.
The list of elements found in living matter is very different from that
for earth’s crust, as shown in the Top Ten. Oxygen, carbon, hydrogen, and
nitrogen form the basis for all biologically important molecules. Some
elements found in the body (called trace elements) are crucial for life,
even though they are present in relatively small amounts (Table 3.2).
For example, chromium helps the body use sugars to provide energy.

One more general comment is important at this point. As we have
seen, elements are fundamental to understanding chemistry. However,
students may be confused by the many different ways that chemists use
the term element illustrated below.

B. Names and Symbols for the Elements

The names of the chemical elements have come from many
sources. Sometimes the names come from descriptions of the element’s
properties, sometimes the name reflects the place where the element was
discovered, and sometimes the name honors a famous scientist.

We often use abbreviations to simplify the written word. For example, it
is much easier to put MA on an envelope than to write out Massachusetts,
and we often write USA instead of United States of America. Likewise,
chemists have invented a set of abbreviations or element symbols for the
chemical elements. These symbols usually consist of the first letter or the
first two letters of the element names. The first letter is always capitalized,
and the second is not. For example,


| fluorine | F       |
| neon     | Ne      |
| oxygen   | O       |
| silicon  | Si      |
| carbon   | C       |

Sometimes, however, the two letters used are not the first two letters in the
name. For example,
zincZn
cadmiumCd
chlorineCl
platinumPt

The symbols for some other elements are based on the original Latin or
Greek name.

| Current Name | Original Name | Symbol |
|--------------+---------------+--------|
| gold         | aurum         | Au     |
| lead         | plumbum       | Pb     |
| sodium       | natrium       | Na     |
| iron         | ferrum        | Fe     |

A list of the most common elements and their symbols is given in
Table 3.3. You can also see the elements represented on a table in the
inside back cover of this text. We will explain the form of this table
(which is called the periodic table) in later chapters.


SECTION 3.2 Atoms and Compounds


As scientists of the eighteenth century studied the nature of materials,
several things became clear:
• Chemical formula
• To understand and illustrate the Law of constant composition
1. Most natural materials are mixtures of pure substances.
2. Pure substances are either elements or combinations of elements
called compounds.

3. A given compound always contains the same proportions (by mass)
of the elements. For example, water always contains 8 g of oxygen
for every 1 g of hydrogen, and carbon dioxide always contains 2.7 g
of oxygen for every 1 g of carbon. This principle became known as the
law of constant composition. It means that a given compound always
has the same composition, regardless of where it comes from.
John Dalton, an English scientist and teacher, was aware of these obser-
vations. In the early 1800s, he offered an explanation for them that became
known as Dalton’s atomic theory. The main ideas of this theory (model)
can be stated as follows:


Dalton’s Atomic Theory
1. Elements are made of tiny particles called atoms.
2. All atoms of a given element are identical.
3. The atoms of a given element are different from those of any other
element.
4. Atoms of one element can combine with atoms of other elements to
form compounds. A given compound always has the same relative
numbers and types of atoms.
5. Atoms are indivisible in chemical processes. That is, atoms are not
created or destroyed in chemical reactions. A chemical reaction simply
changes the way the atoms are grouped together.
Dalton’s model successfully explained important observations such
as the law of constant composition. This law makes sense because if a
compound always contains the same relative numbers of atoms, it will
always contain the same proportions by mass of the various elements.

Like most new ideas, Dalton’s model was not accepted immediately.
However, Dalton was convinced that he was right and used his model to predict
how a given pair of elements might combine to form more than one com-
pound. Dalton pictured compounds as collections of atoms. For example,
nitrogen and oxygen might form a compound containing one atom of
nitrogen and one atom of oxygen (written NO), a compound containing two
atoms of nitrogen and one atom of oxygen (written N2O), or a compound
containing one atom of nitrogen and two atoms of oxygen (written NO_2).



When the existence of these substances was verified, it was a triumph for
Dalton’s model. Because Dalton was able to predict correctly the formation
of multiple compounds between two elements, his atomic theory became
widely accepted.

B. Formulas of Compounds
A compound is a distinct substance that is composed of the atoms of
two or more elements and always contains exactly the same relative masses
of those elements. In light of Dalton’s atomic theory, this statement simply
means that a compound always contains the same relative numbers of
atoms of each element. For example, water always contains two hydrogen
atoms for each oxygen atom.
The types of atoms and the number of each type in each unit (molecule)
of a given compound are conveniently expressed by a chemical formula.
In a chemical formula, the atoms are indicated by the element
symbols and the number of each type of atom is indicated by a
subscript, a number that appears to the right of and below the
symbol for the element.

READING TIP
Here, relative refers to
ratios.

Compound
A substance made of
two or more different
elements joined together
in a speciﬁc way

The formula for water is written H2O, indicating that each molecule
of water contains two atoms of hydrogen and one atom of oxygen (the subscript 1 is always understood and not written). Following are some
general rules for writing formulas:


SECTION 3.3
Atomic Structure
Key TermsObjectives
• Electrons• To learn about the internal parts of an atom
• Nuclear atom• To understand Rutherford’s experiment
• Nucleus• To describe some important features of subatomic particles
• Proton• To learn about the terms isotope, atomic number, and mass number
• Neutron• To understand the use of the symbol ZA X to describe a given atom
• Isotopes
• Atomic number
• Mass number
A. The Structure of the Atom
Dalton’s atomic theory, proposed in the early 1800s, provided such a
convincing explanation for the composition of compounds that it became
generally accepted. Scientists came to believe that elements consist of atoms
and that compounds are a specific collection of atoms bound together in some
way. As does any new theory, Dalton’s model of the atom spawned many
new questions, including “What causes atoms to ‘stick together’ to form
compounds?” and “What is an atom like?” An atom might be a tiny ball of
matter that is the same throughout with no internal structure—like a ball
bearing. Or the atom might be composed of parts—it might be made up of
a number of subatomic particles. However, if the atom contains parts, there
should be some way to break up the atom into its components.
Many scientists pondered the nature of the atom during the 1800s, but
it was not until almost 1900 that convincing evidence became available to
show that the atom has a number of different parts.
Active Reading Question
What are some questions that Dalton’s model of the atom does
not answer?
Thomson’s Experiment
Electron
A negatively charged
subatomic particle
Figure 3.1
Schematic of a cathode ray
tube. A stream of electrons
passes between the
electrodes. The fast-moving
particles excite the gas in
the tube, causing a glow
between the plates.
In the late 1890s, a British physicist named J. J. Thomson used a
cathode ray tube (see Figure 3.1) to show that the atoms of any element
can be made to emit tiny negative particles. (He knew they had a negative
charge because he could show that they were repelled by the negative part
of an electric field.) Thus he concluded that all types of atoms must contain
these negative particles, which are now called electrons.
On the basis of his results, Thomson wondered what an atom must
be like. Although atoms contain these tiny negative particles, he also
knew that whole atoms are not
Source of
negatively or positively charged.
electrical
potential
He concluded that the atom must
also contain positive particles that
Stream of negative
particles (electrons)
balance exactly the negative charge
(–)
carried by the electrons, giving the
(+)
atom a zero overall charge.

The Plum Pudding Model
Spherical cloud of
positive charge
Given J. J. Thomson’s results, it was natural to wonder what the atom
might look like. J. J. Thomson and William Thomson (better known as Lord
Kelvin, and no relation to J. J.) are credited with proposing that the atom
might be something like plum pudding (a pudding with raisins randomly
distributed throughout). They reasoned that the atom might be thought of
as a uniform “pudding” of positive charge with enough negative electrons
scattered within to counterbalance that positive charge (see Figure 3.2).
Thus the plum pudding model of the atom came into being.
Rutherford’s Experiment
If you had taken this course in 1910, the plum pudding model would
have been the only picture of the atom described. However, our ideas about
the atom were changed dramatically in 1911 by a physicist named Ernest
Rutherford, who learned physics in J. J. Thomson’s laboratory in the late
1890s. By 1911 Rutherford had become a distinguished scientist with many
important discoveries to his credit. One of his main areas of interest
involved alpha particles ( particles), positively charged particles with a
mass approximately 7500 times that of an electron. In studying the flight of
these particles through air, Rutherford found that some of the  particles
were deflected by something in the air. Puzzled by this observation, he
designed an experiment that involved directing  particles toward a thin
metal foil. Surrounding the foil was a detector coated with a substance that
produced tiny flashes wherever it was hit by an  particle (see Figure 3.3).
The results of the experiment were very different from those Rutherford
anticipated. Although most of the  particles passed straight through the
foil, some of them were deflected at large angles, as shown in Figure 3.3,
and some were reflected backward.
This outcome was a great surprise to Rutherford. (He described this
result as comparable to shooting a gun at a piece of paper and having the
bullet bounce back.) Rutherford knew that if the plum pudding model of
the atom were correct, the massive  particles would crash through the thin
foil like cannonballs through paper (as shown in Figure 3.4a). So he
expected the  particles to travel throug
